# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
     ## - run: npm ci
      ##- run: npm run build --if-present
      ## - run: npm test
      - name: npm ci client
        working-directory: client
        run: npm ci
      ##- name: test client
      ##  working-directory: client
      ##  run: npm run test
      - name: npm ci server
        working-directory: server
        run: npm ci
      ##- name: test server
      ##  working-directory: server
      ##  run: npm run test
  test:
    runs-on: ubuntu-latest

    strategy:
     matrix:
      node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm ci client
      working-directory: client
      run: npm ci
    - name: npm run build client
      working-directory: client
      run: npm run build --if-present
    - name: npm run test client
      working-directory: client
      run: npm test
    - name: npm ci server
      working-directory: server
      run: npm ci
    - name: npm run build server
      working-directory: server
      run: npm run build --if-present
    - name: npm run test server
      working-directory: server
      run: npm test